name: CI - Dockge-plus

on:
  push:
    branches: [master]
    paths-ignore:
      - '*.md'
      - 'docs/**'
  pull_request:
    branches: [master]
    paths-ignore:
      - '*.md'
      - 'docs/**'

jobs:
  ci:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node: [22]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Configure Git for Windows
        if: runner.os == 'Windows'
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Check Typescript
        run: npm run check-ts

      - name: Test
        if: runner.os == 'Linux'
        run: npm test

      - name: Build
        run: npm run build:frontend
