name: Release - Docker Hub

on:
  push:
    tags:
      - 'v*'

permissions: {}

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Extract version from tag
        id: version
        run: echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm clean-install --no-fund

      - name: Build frontend
        run: npm run build:frontend

      - name: Build and push base image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Base.Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: mrash14/dockge-plus:base
          cache-from: type=gha,scope=base
          cache-to: type=gha,mode=max,scope=base

      - name: Build and push healthcheck image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/BuildHealthCheck.Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: mrash14/dockge-plus:build-healthcheck
          cache-from: type=gha,scope=healthcheck
          cache-to: type=gha,mode=max,scope=healthcheck

      - name: Build and push release image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          target: release
          tags: |
            mrash14/dockge-plus:latest
            mrash14/dockge-plus:${{ steps.version.outputs.VERSION }}
          cache-from: type=gha,scope=release
          cache-to: type=gha,mode=max,scope=release

